# Generated by Django 3.1.3 on 2020-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.TextField()),
                ('EId', models.TextField()),
                ('EmpName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('doj', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('desgn', models.TextField()),
                ('bname', models.CharField(max_length=40)),
                ('hcity', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('pswd', models.CharField(max_length=10)),
                ('leaveTaken', models.IntegerField()),
                ('aic', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MId', models.TextField()),
                ('userName', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('compName', models.CharField(max_length=50)),
                ('secretPswd', models.TextField()),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
