# Generated by Django 3.1.3 on 2020-11-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='aic',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='pswd',
        ),
    ]
